### ISSUE TITLE
False positives in unclosed entities check

### ISSUE THREAD

**Issue by emersonrp** [petdance/html-lint#34]
The unclosed-entities logic makes a big alternation regex of HTML entities (as provided by HTML::Entities) and then checks whether the HTML contains any of those not followed with a semicolon.

This logic breaks, though, on the valid entity &amp;sup2; because &amp;sup; is also a valid entity and therefore triggers the regex when it sees "&amp;sup" followed by a 2 instead of a semicolon.

**Comment by petdance** [comment]
This is fixed in 9abd7d8.
