### ISSUE TITLE
Spurious messages of uninitialized values

### ISSUE THREAD

**Issue by ylavoie** [petdance/html-lint#46]
strict mode complain about uninitialized values:
- Use of uninitialized value $type in lc at /usr/share/perl5/HTML/Lint/Parser.pm line 401.
- Use of uninitialized value $val in substitution iterator at /usr/share/perl5/HTML/Lint/Error.pm line 113.

**Comment by petdance** [comment]
Can you please provide more information?  The HTML that was being parsed, and a program that parses it?

**Comment by petdance** [comment]
This is now fixed.  Thanks.
