### ISSUE TITLE
Undeclared dependency on autodie

### ISSUE THREAD

**Issue by andk** [petdance/html-lint#63]
As per subject. Grep:

http://search.cpan.org/grep?release=HTML-Lint-2.27_01;string=autodie;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/90471958

**Comment by petdance** [comment]
Thanks for this.  @shlomif, 20291f17 is the culprit here.  I will address it.

**Comment by petdance** [comment]
I've uploaded 2.27_02 to CPAN.  Thanks.
