### ISSUE TITLE
Incorrectly claims charset isn't valid for <meta>

### ISSUE THREAD

**Issue by nigelhorne** [petdance/html-lint#64]
This statement in the <head>:

    <meta charset="utf-8">

gives:

    (3:1): Unknown attribute "charset" for tag <meta>

Which I don't believe is true in the latest version of HTML (HTML5).  See for example, https://www.w3schools.com/TAGs/att_meta_charset.asp.  I realize that you clearly say it only supports HTML4, but HTML5 has been out there for so long that now is the time to support it.

**Comment by petdance** [comment]
That's true.  HTML::Lint does not support HTML 5.  It would be great if it did, but as of right now it doesn't.

**Comment by petdance** [comment]
Please take a look at https://github.com/petdance/html-tidy5
