### ISSUE TITLE
bin/weblint won't accept - as filename argument to read from stdin

### ISSUE THREAD

**Issue by ferdnyc** [petdance/html-lint#65]
The help for the `bin/weblint` script claims that it supports reading from stdin with a filename of "-" on the command line, but in practice (using weblint from HTML::Lint 2.30 under Perl 5.26.2 on Fedora 28) that no longer works:

```console
$ echo "<p>Foo<br>Bar</p>" | /usr/bin/weblint -                                                      
Can't open -: No such file or directory at /usr/bin/weblint line 60.
```

The culprit appears to be the form of `open()` being used:
```perl
    if ( $url =~ /^https?:/ ) {
        # [...]
    }
    else {
        open( my $fh, '<', $url ) or die "Can't open $url: $!";
        @lines = <$fh>;
        close $fh or die $!;
    }
```

Though that line of code is 10 _years_ old, so it's surprising if nobody noticed an issue until now.

Possibly this is a recent change to Perl's `open()` semantics. Perhaps someone read the documentation and noticed that `open()` is only documented to accept dashes in the two- and one-argument forms, but NOT the three, and conformed the code to match. From `perldoc -f open`:
> In the two-argument (and one-argument) form, opening "<-" or "-" opens STDIN and opening ">-" opens STDOUT.

Sure enough:

```console
$ echo "<p>Foo<br>Bar</p>" | perl -e \
'$FILENAME = "-"; open (FILENAME) or die "$!"; my @input = <FILENAME>; print STDOUT @input;'
<p>Foo<br>Bar</p>

$ echo "<p>Foo<br>Bar</p>" | perl -e \
'open (my $fh, "-") or die "$!"; my @input = <$fh>; print STDOUT @input;' 
<p>Foo<br>Bar</p>

$ echo "<p>Foo<br>Bar</p>" | perl -e \
'open (my $fh, "<", "-") or die "$!"; my @input = <$fh>; print STDOUT @input;'
No such file or directory at -e line 1.
```

**Comment by ferdnyc** [comment]
OK if it is a change, it wasn't a recent one: [it's been this way since at least 2015](https://stackoverflow.com/questions/30540998/2-vs-3-argument-open-with).

**Comment by ferdnyc** [comment]
> Can I interest you in using HTML::Tidy5? It does far far more than HTML::Lint does and it handles HTML5 and I'll actually be working to make improvements to it.

Doesn't appear to be packaged for Fedora, surprisingly! They are packaging your [HTML::Tidy](https://github.com/petdance/html-tidy/) which I probably should've been using instead (though that wouldn't have helped in this case, since I've just now discovered that its `webtidy` also has this same issue; I'll probably fire off a patch over there as well) but it seems HTML::Tidy5 is nowhere to be found.

I'll point the `perl-HTML-Tidy` packagers at HTML::Tidy5 and let them know it's a recommended replacement, hopefully we can get it into Fedora. I certainly have no objections to using it, and it sounds like the much more modern/supported/capable choice by far, but pure (though perhaps not True) laziness tends to skew my choices towards whatever's available in the repos. :grin:

**Comment by petdance** [comment]
I've fixed this.  It will be in 2.32.
